[project]
name = "cvmaker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1",
    "pydantic[email]>=2.7",
    "fastmcp>=2.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]